### PR TITLE
Blender Preprocessing Support

### PR DESCRIPTION
**Pull request by afshawnlotfi**
Hi I remember with the wing from earlier you had to do some preprocessing on it with Decimate in Blender before running it to make it easier on the algorithm. I added blender preprocessing support so that you can put a preprocessor function that uses Blender script to automate getting your 3D object just the way you want it before running like so:

```python
def PREPROCESSOR_FUNC(mesh):
    modifier = mesh.modifiers.new('decimate', 'DECIMATE')
    modifier.ratio=0.1
    modifier.use_collapse_triangulate=True
```

### CODE REVIEW

**Comment by afshawnlotfi** [comment]
Hold up for some reason I am getting this error for ``python main.py -c examples/wing_config.yml``:

```
Traceback (most recent call last):
  File "main.py", line 119, in <module>
    run(starter)
  File "main.py", line 70, in run
    tree = connector_placer.insert_connectors(tree, state)
  File "/workspaces/pychop3d/pychop3d/connector.py", line 157, in insert_connectors
    new_node.children[pi].part = insert_slot(new_node.children[pi].part, slot)
  File "/workspaces/pychop3d/pychop3d/connector.py", line 188, in insert_slot
    raise Exception("Couldn't insert slot")
Exception: Couldn't insert slot
```
Will need to look into it

**Comment by gregstarr** [comment]
Ok sounds good. When debugging, check out the function in `utils` called `preview_tree`. It helps visualize what the chopped object looks like and you can specify additional trimesh objects to add to the scene.

Additionally, I know that the pytest converage is crap right now, but if you are adding new features I think it would be best if it is accompanied by a pytest test. Have you used pytest before?

**Comment by afshawnlotfi** [comment]
haha just about to say the tests weren't working but see through the branch conflict you fixed it right on time!

**Comment by gregstarr** [comment]
Hey this looks good so far. I just added a CONTRIBUTING file which lays out some guidelines for PRs and issues. Basically just to add a test and documentation for the new feature and run the test suite (now that it works).

**Comment by afshawnlotfi** [comment]
Alright so I finished my tests. I changed ``regression_test_data`` to ``test_data`` to make it more generic. I broke your tests however because I am loading in my config files for tests that my test is getting called before and messing up your `` Configuration.config``. I didn't want to assume anything so I left it for you to fix and load in your own config specific for that test. I think that the `` Configuration.config`` shouldn't have any dependence on other tests, which from what I am seeing is the case?

I also changed the backslashes to forward-slashes to be compliant with both Unix and Windows systems

**Comment by afshawnlotfi** [comment]
Alright fixed all the tests for now by restoring the original ``Configuration.config`` back after the test, but just a general rule of thumb to try and make tests independent of each other's static variable ``Configuration.config``

**Comment by gregstarr** [comment]
Yes you are correct, I will try to make a function-level config fixture which restores defaults after each test function. Thanks for the PR

**Comment by gregstarr** [comment]
Hello, thanks again for the PR, can you explain how preprocessing works? It seems like the user can create a file of the `.py.template` type with a function called `PREPROCESSOR_FUNC` in it, then point to this file in the config yaml using the key `preprocessor`. The `PREPROCESSOR_FUNC` must take in the `bpy.data.objects[0]` object which seems like the only object in the scene (I don't really know blender scripting at all). Then it can modify it in-place in any way it wants.

Do I have this right?

**Comment by gregstarr** [comment]
added config fixture in #37

**Comment by afshawnlotfi** [comment]
Yes your understanding is correct. The mesh object being passed into the function is essentially the Blender mesh you are transforming with a modifier. Here is a good tutorial to see what is going on. The mesh being passed in is the obj in this example: [https://github.com/njanakiev/blender-scripting#simple-sphere](https://github.com/njanakiev/blender-scripting#simple-sphere) and also here [https://github.com/njanakiev/blender-scripting#rugged-donut](https://github.com/njanakiev/blender-scripting#rugged-donut). I actually didn't know Blender script before writing this, but it seemed pretty straightforward once you have all the boilerplate code which I provided in the template and all you have to do it change the mesh as you desire

**Pull request merged**
