### PR TITLE
Docker and devcontainer support

### PR DESCRIPTION
**Pull request by afshawnlotfi**
Better code environment so we do not have to worry about operating specific version problems, keeping package from breaking, etc.

### CODE REVIEW

**Comment by gregstarr** [comment]
This is awesome, thanks for making this change. I have never used docker before, can you briefly explain how I can test this on my computer?

**Comment by afshawnlotfi** [comment]
First get Docker from [https://www.docker.com/products/docker-desktop](https://www.docker.com/products/docker-desktop)

If you want to have dev container support with an editor
1. Get Visual Studio Code [https://code.visualstudio.com/](https://code.visualstudio.com/)
2. Get remote containers plugin :
image
3. Reload Editor
4. Open this repo in editor and you should see popup to reopen in devcontainer and everything will get setup for you
image

If you want to just access container from Dockerfile in the terminal
1. move into root directory where Dockerfile is
2. to build Dockerfile run ``docker build --tag $username/pychop3d .``
3. to run Docker container you just built run ``docker run -it $username/pychop3d bin/bash``

You will need to clone this repo with just the raw Docker image. I just setup the environment. ``git clone https://github.com/gregstarr/pychop3d.git `` and ``cd https://github.com/gregstarr/pychop3d.git`` and test with ``python main.py``

4. if you would like to push the newly built docker image to the cloud create a docker account
5. login in the terminal to the docker account with ``docker login``
6. then run ``docker push  $username/pychop3d``

NOTE: $username is your docker username if you would like to push this to Docker hub later

I have actually built the Docker container so if you want to quickly just try this out and you have Docker installed you can run:
``docker run -it afshawnlotfi/pychop3d bin/bash`` to get a Docker terminal with everything setup

You can actually link your Github with Docker hub and choose this repo and Docker will automatically create the image in the cloud for you anytime there are changes to the Dockerfile.

Docker is a great platform and I have stopped installing dev stuff on my main system all together with the help of vscode devcontainers since I can just put all the packages I need in a Dockerfile within the project and everything gets installed when I need it in it's own isolated container.

If you have any questions please let me know. Would be happy to help!

**Comment by gregstarr** [comment]
Awesome, thanks for the guide, I have to update windows in order to install Docker. After I do that, I will give this a try and let you know if I have any issues.

**Comment by gregstarr** [comment]
Great instructions. I was able to get Docker, set up my own container, clone the repo into the container, then run `main.py`. Finally, I copied the resulting STL files back to my computer and verified that they looked correct. I will merge in the PR.

**Comment by paulonasc7** [comment]
Can I run this in MacOS? Followed steps 1-4, but when building the image, I get this error "Preparing metadata (pyproject.toml): finished with status 'error'". The error is actually longer but I think this is the important part. Any idea on how to solve it?

**Comment by gregstarr** [comment]
Can you post the whole error?

**Comment by paulonasc7** [comment]
The error actually happens when installing scipy==1.5.2. I can solve the problem by changing requirements to scipy==1.7.3 for example. Nevertheless, then I get a similar error for shapely==1.7.1. The error below is the one that I get for scipy. Sorry, but it is really long. 

```
#8 21.97 Collecting scipy==1.5.2
#8 21.98   Downloading scipy-1.5.2.tar.gz (25.4 MB)
#8 28.44      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 25.4/25.4 MB 3.9 MB/s eta 0:00:00
#8 29.66   Installing build dependencies: started
#8 94.02   Installing build dependencies: still running...
#8 129.7   Installing build dependencies: finished with status 'done'
#8 129.7   Getting requirements to build wheel: started
#8 129.8   Getting requirements to build wheel: finished with status 'done'
#8 129.8   Preparing metadata (pyproject.toml): started
#8 130.2   Preparing metadata (pyproject.toml): finished with status 'error'
#8 130.2   error: subprocess-exited-with-error
#8 130.2   
#8 130.2   × Preparing metadata (pyproject.toml) did not run successfully.
#8 130.2   │ exit code: 1
#8 130.2   ╰─> [137 lines of output]
#8 130.2       lapack_opt_info:
#8 130.2       lapack_mkl_info:
#8 130.2       customize UnixCCompiler
#8 130.2         libraries mkl_rt not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       openblas_lapack_info:
#8 130.2       customize UnixCCompiler
#8 130.2       customize UnixCCompiler
#8 130.2         libraries openblas not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       openblas_clapack_info:
#8 130.2       customize UnixCCompiler
#8 130.2       customize UnixCCompiler
#8 130.2         libraries openblas,lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       atlas_3_10_threads_info:
#8 130.2       Setting PTATLAS=ATLAS
#8 130.2       customize UnixCCompiler
#8 130.2         libraries tatlas,tatlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries tatlas,tatlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries tatlas,tatlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       atlas_3_10_info:
#8 130.2       customize UnixCCompiler
#8 130.2         libraries satlas,satlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries satlas,satlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries satlas,satlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       <class 'numpy.distutils.system_info.atlas_3_10_info'>
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       atlas_threads_info:
#8 130.2       Setting PTATLAS=ATLAS
#8 130.2       customize UnixCCompiler
#8 130.2         libraries ptf77blas,ptcblas,atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries ptf77blas,ptcblas,atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries ptf77blas,ptcblas,atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       <class 'numpy.distutils.system_info.atlas_threads_info'>
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       atlas_info:
#8 130.2       customize UnixCCompiler
#8 130.2         libraries f77blas,cblas,atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/local/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries f77blas,cblas,atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib
#8 130.2       customize UnixCCompiler
#8 130.2         libraries f77blas,cblas,atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack_atlas not found in /usr/lib/aarch64-linux-gnu
#8 130.2       <class 'numpy.distutils.system_info.atlas_info'>
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       lapack_info:
#8 130.2       customize UnixCCompiler
#8 130.2         libraries lapack not found in ['/usr/local/lib', '/usr/lib', '/usr/lib/aarch64-linux-gnu']
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       lapack_src_info:
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2         NOT AVAILABLE
#8 130.2       
#8 130.2       setup.py:462: UserWarning: Unrecognized setuptools command ('dist_info --egg-base /tmp/pip-modern-metadata-lbd71_ao'), proceeding with generating Cython sources and expanding templates
#8 130.2         ' '.join(sys.argv[1:])))
#8 130.2       Running from SciPy source directory.
#8 130.2       /tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
#8 130.2           Atlas (http://math-atlas.sourceforge.net/) libraries not found.
#8 130.2           Directories to search for the libraries can be specified in the
#8 130.2           numpy/distutils/site.cfg file (section [atlas]) or by setting
#8 130.2           the ATLAS environment variable.
#8 130.2         self.calc_info()
#8 130.2       /tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
#8 130.2           Lapack (http://www.netlib.org/lapack/) libraries not found.
#8 130.2           Directories to search for the libraries can be specified in the
#8 130.2           numpy/distutils/site.cfg file (section [lapack]) or by setting
#8 130.2           the LAPACK environment variable.
#8 130.2         self.calc_info()
#8 130.2       /tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/numpy/distutils/system_info.py:624: UserWarning:
#8 130.2           Lapack (http://www.netlib.org/lapack/) sources not found.
#8 130.2           Directories to search for the sources can be specified in the
#8 130.2           numpy/distutils/site.cfg file (section [lapack_src]) or by setting
#8 130.2           the LAPACK_SRC environment variable.
#8 130.2         self.calc_info()
#8 130.2       Traceback (most recent call last):
#8 130.2         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
#8 130.2           main()
#8 130.2         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
#8 130.2           json_out['return_val'] = hook(**hook_input['kwargs'])
#8 130.2         File "/usr/local/lib/python3.7/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
#8 130.2           return hook(metadata_directory, config_settings)
#8 130.2         File "/tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 188, in prepare_metadata_for_build_wheel
#8 130.2           self.run_setup()
#8 130.2         File "/tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 282, in run_setup
#8 130.2           self).run_setup(setup_script=setup_script)
#8 130.2         File "/tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 174, in run_setup
#8 130.2           exec(compile(code, __file__, 'exec'), locals())
#8 130.2         File "setup.py", line 583, in <module>
#8 130.2           setup_package()
#8 130.2         File "setup.py", line 579, in setup_package
#8 130.2           setup(**metadata)
#8 130.2         File "/tmp/pip-build-env-dnwsqmu3/overlay/lib/python3.7/site-packages/numpy/distutils/core.py", line 135, in setup
#8 130.2           config = configuration()
#8 130.2         File "setup.py", line 477, in configuration
#8 130.2           raise NotFoundError(msg)
#8 130.2       numpy.distutils.system_info.NotFoundError: No lapack/blas resources found.
#8 130.2       [end of output]
#8 130.2   
#8 130.2   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 130.2 error: metadata-generation-failed
#8 130.2 
#8 130.2 × Encountered error while generating package metadata.
#8 130.2 ╰─> See above for output.
#8 130.2 
#8 130.2 note: This is an issue with the package mentioned above, not pip.
#8 130.2 hint: See above for details.
```

**Comment by paulonasc7** [comment]
This is the error that I get for shapely.

```
#8 38.17 Collecting shapely==1.7.1
#8 38.19   Downloading Shapely-1.7.1.tar.gz (383 kB)
#8 38.31      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 383.2/383.2 KB 3.0 MB/s eta 0:00:00
#8 38.35   Preparing metadata (setup.py): started
#8 38.45   Preparing metadata (setup.py): finished with status 'error'
#8 38.45   error: subprocess-exited-with-error
#8 38.45   
#8 38.45   × python setup.py egg_info did not run successfully.
#8 38.45   │ exit code: 1
#8 38.45   ╰─> [12 lines of output]
#8 38.45       Failed `CDLL(libgeos_c.so.1)`
#8 38.45       Failed `CDLL(libgeos_c.so)`
#8 38.45       Traceback (most recent call last):
#8 38.45         File "<string>", line 36, in <module>
#8 38.45         File "<pip-setuptools-caller>", line 34, in <module>
#8 38.45         File "/tmp/pip-install-j5u6lm8v/shapely_2b49464175c24e67805a51d43255eed4/setup.py", line 85, in <module>
#8 38.45           from shapely._buildcfg import geos_version_string, geos_version, \
#8 38.45         File "/tmp/pip-install-j5u6lm8v/shapely_2b49464175c24e67805a51d43255eed4/shapely/_buildcfg.py", line 170, in <module>
#8 38.45           fallbacks=['libgeos_c.so.1', 'libgeos_c.so'])
#8 38.45         File "/tmp/pip-install-j5u6lm8v/shapely_2b49464175c24e67805a51d43255eed4/shapely/_buildcfg.py", line 164, in load_dll
#8 38.45           libname, fallbacks or []))
#8 38.45       OSError: Could not find library geos_c or load any of its variants ['libgeos_c.so.1', 'libgeos_c.so']
#8 38.45       [end of output]
#8 38.45   
#8 38.45   note: This error originates from a subprocess, and is likely not a problem with pip.
#8 38.45 error: metadata-generation-failed
#8 38.45 
#8 38.45 × Encountered error while generating package metadata.
#8 38.45 ╰─> See above for output.
#8 38.45 
#8 38.45 note: This is an issue with the package mentioned above, not pip.
#8 38.45 hint: See above for details.
```

**Comment by gregstarr** [comment]
Ok, sorry you are having this issue. I think I will need to verify the docker container on my end. 

In the mean time I would try to set up your environment using these steps:

Install these packages on your Mac, I am not familiar with MacOS so you will have to look up  how to do that.
- wget 
- libspatialindex-dev 
- libglu1
- libxrender1
- libxtst6
- libxi6
    
Then download version 2.79b of blender and make sure it is on your path
  
Then make a python virtual environment and follow these steps:
- python -m pip install --upgrade pip
- pip install -r requirements.txt

**Comment by paulonasc7** [comment]
There is always the chance that I'm doing something wrong, but I don't think so. The steps with Docker are kinda straightforward, so I think I'm doing everything right.

I'll follow what you said and then I'll let you know.

**Comment by gregstarr** [comment]
Here is something you can try:
1. switch to the `docker` branch
2. download blender `blender-2.79b-linux-glibc219-x86_64.tar.bz2` from [here](https://download.blender.org/release/Blender2.79/)
3. put the blender file into the pychop directory
4. open a terminal in the pychop directory and run `docker build .`

Then I think you should be able to use that docker image. I made the image successfully on my work computer, but I haven't figured out how to push it to docker hub around my company proxy / firewall.

**Comment by paulonasc7** [comment]
Followed this and I get the exact same error for scipy, except that now I get the error in the Terminal instead of in VS code, but that's obvious.

Well, looks like I'll need to figure this out, maybe the problem is on my side and not with the code.

Anyway, I used `docker run -it afshawnlotfi/pychop3d bin/bash`, as [afshawnlotfi](https://github.com/afshawnlotfi) suggested and I think I was able to successfully create the image. I'm still trying to understand if it works cause I never worked with Docker before.

**Comment by gregstarr** [comment]
Ok, let me know if you are able to proceed with afshawnlotfi's image. Otherwise I can try to create a new one.

**Comment by paulonasc7** [comment]
So, I actually tried with a Windows environment and I was able to create a virtual environment in Pycharm and install all requirements and build all dependencies, including rtree==0.9.4, which is the problem that I always get when trying to create a virtual environment using MacOS. I'm not actually running it because the computer where I have Windows is too slow, but since it was able to successfully install all the requirements, I believe it should run without problems. Looks like it is some kind of compatibility problem with MacOS, perhaps with the rtree package. I'll try to investigate this.

**Comment by paulonasc7** [comment]
Just a little update. @gregstarr  If you want feel free to change this comment to another place cause this is probably not the best place. Or if you can't do it just tell me and I'll do it myself.

Instead of creating a new environment using Virtualenv in Pycharm, I created a new environment in Conda. After going back and forth with some of the requirements, I was actually able to install all of them correctly, including rtree==0.9.4. It seems like there is some kind of problem with rtree, and for macOS you really need to use conda, as stated  [here](https://stackoverflow.com/questions/68464704/attributeerror-dlsymrtld-default-error-getlasterrornum-symbol-not-found).

Then I ran the example for the bunny_config and everything went perfect. Then I tried the shoerack_config, and got the same error that I was having with rtree==0.9.7. So, after all, looks like I've been going back and forth with the requirements and maybe the problem comes from another place.

After some minutes running the shoerack_config, I get this error "Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)"

**Comment by gregstarr** [comment]
Ok I'm glad you were able to get some of the examples to work. Like I said in my email, this software is not very reliable and improving its reliability has been on my todo list for a very long time. If you are determined to get the shoerack to work, I would try messing around with the settings. 

The ultimate solution would be to trace the crash to a specific operation in the process. Because you get a non-python error, it must be happening during a call to an underlying c library. There could be a bug in the library which we would need to figure out how to fix or work around. If you are interested, give it a shot. 

I'm glad someone is interested in this project so I will take a look myself, but it may be a few weeks.

**Pull request merged**
